ACLabs1/FakeTravian/Controllers/MinesController.cs
using BusinessLogic;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FakeTravian.Controllers
{
    [Authorize]
    public class MinesController : Controller
    {
        MinesService ms;

        public MinesController()
        {
           ms = new MinesService();
        }

        // GET: Mines
        public ActionResult Index()
        {
            var userId = this.User.Identity.GetUserId();
            var city = ms.UpdateResources(userId);
            return View(city);
        }

        /*
        public ActionResult Details(int mineId)
        {
            var mine = mr.GetMine(mineId);
            return View(mine);
        }

        [HttpPost]
        public ActionResult Upgrade(int mineId, bool fastUpgrade)
        {
            var mine = this.dbContext.Mines.Find(mineId);
            var city = mine.City;
            var needed = mine.GetUpgradeRequirements();
            var have = city.Resources;

            if(fastUpgrade)
            {
                needed = needed.Select(n => (amount: n.amount * 10, type: n.type)).ToArray();
            }
            var r = needed.Join(have, n => n.type, h => h.Type, (n, h) => (needed: n, have: h));

            if(!r.All(_=> _.needed.amount < _.have.Value))
            {
                return View(new Models.MessageViewModel
                {
                    Message = $"You do not have enough resources"
                });
            }

            foreach (var item in r)
            {
                item.have.Value -= item.needed.amount;
            }

            mine.Level++;
            mine.UpgradeCompletesAt = DateTime.Now.AddHours(0.5 * mine.Level);
            this.dbContext.SaveChanges();

            return View(new Models.MessageViewModel
            {
                Message = $"Upgrade Successfull"
            });
        }
        */
    }
}

ACLabs1/FakeTravian/Views/Mines/Details.cshtml
@model FakeTravian.Models.Mine

@{
    ViewBag.Title = "Details";
    this.Layout = null;
}

<h2>Details</h2>

@if (this.Model.Type == FakeTravian.Models.ResourceType.Wheat)
{ 
    <h3>Wheat</h3>
    <p>Your population`s food is produced here. By increasing the farm`s level, you increase its crop production.</p>
}
else if (this.Model.Type == FakeTravian.Models.ResourceType.Clay)
{
    <h3>Clay</h3>
    <p>Clay is produced here. By increasing its level, you increase the clay production.</p>
}
else if (this.Model.Type == FakeTravian.Models.ResourceType.Iron)
{
    <h3>Iron</h3>
    <p>Here miners produce the precious resource of iron. By increasing the mine`s level, you increase the iron production.</p>
}
else if (this.Model.Type == FakeTravian.Models.ResourceType.Wood)
{
    <h3>Wood</h3>
    <p>The woodcutter cuts down trees in order to produce lumber. The further you extend the woodcutter, the more lumber is produced.</p>
}

<img src="~/Content/img/mine-@(this.Model.Type).png" />
<p>Current production: @(this.Model.Level * 13)</p>
<p>Production for next level: @((this.Model.Level + 1) * 13)</p>

@using (Html.BeginForm("Upgrade", "Mines"))
{
    //<input name="mineId" value="10" type="hidden"/>
    @Html.HiddenFor(m => m.MineId)
    <div>Do a fast upgrade ?: @Html.CheckBox("fastUpgrade") </div>
    <button type="submit">Upgrade</button>
}

ACLabs1/FakeTravian/Views/Mines/Index.cshtml
@model DataAccess.City

@{
    ViewBag.Title = "Mines";
}

<table>
    <tr>
        @foreach (var res in this.Model.Resources)
        {
            <td class="res-img @(res.Type)"><img src="~/Content/img/icon-@(res.Type).png" /></td>
            <td class="res-value @(res.Type)">@res.Value.ToString("n4")</td>
            <td class="res-update @(res.Type)">@res.LastUpdate</td>
        }
    </tr>
</table>
<table class="mines">
    @foreach (var mine in this.Model.Mines)
    {
        <tr class="@(mine.Type)">
            <td><img src="~/Content/img/icon-@(mine.Type).png"/></td>
            <td>@mine.Type</td>
            <td>@mine.Level</td>
            <td><span class="mine-details-btn" data-mine-id="@mine.MineId">Details</span></td>
            <td class="hourProduction">@mine.GetProductionPerHour()</td>
        </tr>
    }
    <div id="mine-details-container">
        <div class="close-btn">X</div>
        <div class="content"></div>
    </div>
</table>
@section Scripts {
    <script src="~/Scripts/Javascript/mines.js"></script>
    <script src="~/Scripts/Date.min.js"></script>
    }

ACLabs1/FakeTravian/Views/Mines/Upgrade.cshtml
@model FakeTravian.Models.MessageViewModel
@{
    ViewBag.Title = "Upgrade";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upgrade</title>
</head>
<body>
    <div> 
    </div>
    <h2>@this.Model.Message</h2>
</body>
</html>